#!/bin/sh

# Copyright 2015-2020 Joel Allen Luellwitz and Andrew Klapp
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

case "$1" in
    configure)

    # Default Linux user and group information
    CAMMON_USER='cammon'
    CAMMON_USER_COMMENT='Cammon Daemon'
    CAMMON_GROUP='cammon'
    GPGMAILER_GROUP='gpgmailer'
    VIDEO_GROUP='video'

    # Add the cammon group
    if ! getent group "$CAMMON_GROUP" >> /dev/null; then
        echo -n "Adding group $CAMMON_GROUP..."
        addgroup --quiet --system "$CAMMON_GROUP" 2> /dev/null
        echo "done"
    fi

    # Add the cammon user
    if ! getent passwd "$CAMMON_USER" >> /dev/null; then
        echo -n "Adding system user $CAMMON_USER..."
        adduser --quiet --system --ingroup "$CAMMON_GROUP" --no-create-home --disabled-password \
            "$CAMMON_USER" 2> /dev/null
        echo "done"
    fi

    # Adjust the user regardless of whether this script created the user or not.
    #   (The user might already exist.)
    usermod -c "$CAMMON_USER_COMMENT" -d "/nonexistent" -g "$CAMMON_GROUP" \
        -G "$GPGMAILER_GROUP","$VIDEO_GROUP" "$CAMMON_USER"
    ;;
esac

systemctl enable cammon || exit 1
systemctl restart cammon || exit 1
