#!/bin/sh

# Copyright 2015-2020 Joel Allen Luellwitz and Andrew Klapp
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

case "$1" in
    configure)

    # Default Linux user and group information
    WATCHMAN_USER='watchman'
    WATCHMAN_USER_COMMENT='Watchman Daemon'
    WATCHMAN_GROUP='watchman'
    GPGMAILER_GROUP='gpgmailer'
    VIDEO_GROUP='video'

    # Add the watchman group
    if ! getent group "$WATCHMAN_GROUP" >> /dev/null; then
        echo -n "Adding group $WATCHMAN_GROUP..."
        addgroup --quiet --system "$WATCHMAN_GROUP" 2> /dev/null
        echo "done"
    fi

    # Add the watchman user
    if ! getent passwd "$WATCHMAN_USER" >> /dev/null; then
        echo -n "Adding system user $WATCHMAN_USER..."
        adduser --quiet --system --ingroup "$WATCHMAN_GROUP" --no-create-home --disabled-password \
            "$WATCHMAN_USER" 2> /dev/null
        echo "done"
    fi

    # Adjust the user regardless of whether this script created the user or not.
    #   (The user might already exist.)
    usermod -c "$WATCHMAN_USER_COMMENT" -d "/nonexistent" -g "$WATCHMAN_GROUP" \
        -G "$GPGMAILER_GROUP","$VIDEO_GROUP" "$WATCHMAN_USER"
    ;;
esac

systemctl enable defaults || exit 1
systemctl restart watchman || exit 1
